name: auth service CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: backend/package-lock.json
          node-version: "20.x"
          cache: "npm"

      - run: npm install
        working-directory: backend

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Start application-specific services using Docker Compose
        run: docker-compose up -d
        working-directory: backend
        continue-on-error: false

      - run: npm test
        working-directory: backend
